#!/bin/bash
set -e
source helpers/apply-patches.bash

script_folder=$(dirname "$0")
pe_manifest="https://github.com/PixelExperience/manifest"
pe_branch="ten"

mkdir -p .repo/local_manifests
ln "$script_folder/local_manifest.xml" .repo/local_manifests/manifest.xml

repo init -u "$pe_manifest" -b "$pe_branch" --depth=1
repo sync -c -j"$threads" --force-sync --no-clone-bundle --no-tags

apply_patches patches
